#!/usr/bin/python3

import serial
import os
import json
import time
import sys

serialName= sys.argv[1]
com = serial.Serial("/dev/" + serialName, 115200, timeout=0.5)
i = 1

def main():
    while True:
        # if keyboard.is_pressed('q'):
                # break
        
        msg = getMsg()
        com.write(msg.encode())
        time.sleep(2)

def getMsg():
    message = os.popen('s-tui -j').read()
    jsonmsg = json.loads(message)

    cpuTemp = jsonmsg['Temp']['Smbusmaster0,0']
    cpuUtil = jsonmsg['Util']['Avg']
    cpuFreq = str(round(float(jsonmsg['Frequency']['Avg'])/1000, 2))
    cpuFan = jsonmsg['Fan']['nct6795,1']

    # msg = "?TCPU=" + cpuTemp + "!?SCPUUTI=" + cpuUtil + "!?SCPUCLK=" + cpuFreq \
        # + "!?CPUFAN=" + cpuFan + "!"
    
    global i
    if i==1:
        i = 2
        return "?TCPU=" + cpuTemp + "!"
    elif i==2:
        i = 3
        return "?SCPUUTI=" + cpuUtil  + "!"
    elif i==3:
        i = 4
        return "?SCPUCLK=" + cpuFreq + "!"
    elif i==4:
        i = 1
        return "?FCPU=" + cpuFan + "!"


    # print(msg)
    # return msg

main()
